### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by AlexiyOrlov** [defold/tutorial-movement#6]
I followed this tutorial, but I get an error with the final code:
```
ERROR:SCRIPT: main/spaceship.script:8: vmath.lengthSqr accepts (vector3|vector4|quat) as argument.
stack traceback:
  [C]:-1: in function length_sqr
  main/spaceship.script:8: in function <main/spaceship.script:7>```

**Comment by JCash** [comment]
The error means that you've passed something other than the supported types to `vmath.length_sqr(self.input)`

What is the value of `self.input` in your code, and how did you assign it?
