### ISSUE TITLE
The background doesn't get rendered

### ISSUE THREAD

**Issue by PsionicAlch** [defold/tutorial-movement#7]
I created a new project using this tutorial. As soon as the project has finished opening up I press Ctrl+B to run the game. Whilst running the game I am met with a black screen like so:

![Screenshot from 2024-01-29 12-22-54](https://github.com/defold/tutorial-movement/assets/34652519/b836fa03-8f45-4c37-87f3-d44f41196213)

To fix the issue I had to change the Z value of the background from -1 to 0. That resulted in me being able to see the background but without the spaceship:

![Screenshot from 2024-01-29 12-25-18](https://github.com/defold/tutorial-movement/assets/34652519/0beb0b1d-29b0-4325-a507-5bced6fca772)

This resulted in a new problem where I couldn't see the spaceship anymore so I changed the Z value for the spaceship from 0 to 1. That, in the end, gave me a working scene where I could see the background image as well as the spaceship:

![Screenshot from 2024-01-29 12-27-45](https://github.com/defold/tutorial-movement/assets/34652519/17cd238f-8b59-4b92-a166-9d4be663450b)

**Comment by AGulev** [comment]
Hi, please take a look our FAQ 
https://defold.com/faq/faq/#q-would-changing-the-view-projection-z-range-to--100-to-100-impact-performance

You don't have to use only round values for Z.


If you want to have bigger Near/Far value, you can change it using one message: 
```
msg.post("@render:", "use_fixed_fit_projection", { near = -100, far = 100 }) -- pick needed values and projection
```
More info is available here:
https://defold.com/manuals/render/

**Comment by PsionicAlch** [comment]
Thank you for the link! 

The issue is that, for a newly created project based off the movement tutorial, I don't see the background until I change the Z value of the background in the inspector.

**Comment by AGulev** [comment]
Ah, it's movement project, right (I didn't check this issue isn't in the main repo) and testing `Side scroller tutrial` project

Thank you for your issue, I'll fix this tutorial project to make it work out of the box.

**Comment by PsionicAlch** [comment]
Yes, it's the movement project. I've worked through the "Side scroller tutorial", "Walking astronaut tutorial", and the "Movement tutorial" today. Thus far only the "Movement tutorial" had the issue where the background didn't appear until I made the changes to the game objects' Z index.

**Comment by AGulev** [comment]
Yes, we made changes in our render_script just a while back, I fixed most of the project which were affected, but probably missed this one. 
Thank you one more time!
